version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo my pipeline stack name ${DEPLOY_PIPELINE_STACK_NAME}...
      - dynamoDbArn=$(aws cloudformation describe-stacks --stack-name ${DEPLOY_PIPELINE_STACK_NAME} --query 'Stacks[0].Outputs[0].OutputValue' --output text)
      - echo my dynamoDbArn is ${dynamoDbArn}
      - sam build --template ${SAM_DEPLOY_TEMPLATE_PATH}
      - ./assume-role.sh ${BUILD_PIPELINE_EXECUTION_ROLE} build-package
      - sam package --s3-bucket ${BUILD_ARTIFACT_BUCKET}
        --region ${BUILD_REGION}
        --output-template-file ${ENV_PACKAGE_TEMPLATE}
artifacts:
  files:
    - ${ENV_PACKAGE_TEMPLATE}
    - assume-role.sh
    - pipeline/*
