build-LineHandlerFunction:
	@ mvn clean install -s settings.xml
	@ cp  ./target/ptt-crawler-1.0.jar $(ARTIFACTS_DIR)
build-PttCrawlerFunction:
	@ mvn clean install -s settings.xml
	@ cp  ./target/ptt-crawler-1.0.jar $(ARTIFACTS_DIR)

