build-LineHandlerFunction:
	@ mvn clean install -s settings.xml
	@ cp -r ./target/classes/* $(ARTIFACTS_DIR)
build-PttCrawlerFunction:
	@ mvn clean install -s settings.xml
	@ cp -r ./target/classes/* $(ARTIFACTS_DIR)

