AWSTemplateFormatVersion: '2010-09-09'
Description: practice-cloudformation
Parameters:
  MyLambdaBucket:
    Type: String
    Default: 'deploy-source-2233'
  MyLambdaObjectKey:
    Type: String
    Default: 'crawler-0.0.1-SNAPSHOT.jar'
Resources:
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: [ 'sts:AssumeRole' ]
            Effect: 'Allow'
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'lambda:*'
                Effect: Allow
                Resource: '*'
  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'my-cloudformation-lambda'
      Handler: 'com.kevin.crawler.LambdaRequestHandler::handleRequest'
      Code:
        S3Bucket: !Ref MyLambdaBucket
        S3Key: !Ref MyLambdaObjectKey
      Runtime: 'java21'
      MemorySize: 256
      Timeout: 120
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: '--add-opens=java.management/sun.management=ALL-UNNAMED'
      Role: !GetAtt [MyLambdaRole, Arn]


