pipeline:
  identifier: Build_kevin5603_PTT_Crawler_1735900232534
  name: Build PTT_Crawler
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: kevin5603/PTT_Crawler
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      ls -al
                      echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: maven build
                  identifier: maven_build
                  spec:
                    shell: Sh
                    command: |-
                      echo "prepare build project..."
                      ls -al
                      echo "cd to ptt-crawler folder..."
                      cd ptt-crawler
                      mvn clean package
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
        type: CI
