Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: com.kevin.crawler.handler.LineMessageHandler
      CodeUri: /Users/kevin.lee/Documents/work/project/ptt-crawler-project/ptt-crawler
      Runtime: java21
      Architectures:
        - x86_64